//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Compras.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Proveedores
    {
        public int ProveedorId { get; set; }
        public string Cedula_RNC { get; set; }
        public string Nombre_comercial { get; set; }
        public Nullable<bool> Estado { get; set; }
    }
}
