//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Compras.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_GetOrdenCompra
    {
        public int Numero_de_orden { get; set; }
        public Nullable<System.DateTime> Fecha_orden { get; set; }
        public Nullable<bool> Estado { get; set; }
        public string Articulo { get; set; }
        public Nullable<int> Cantidad { get; set; }
        public string UnidadMedida { get; set; }
        public Nullable<decimal> Costo { get; set; }
        public string Usuario { get; set; }
        public Nullable<bool> Enviado { get; set; }
    }
}
